### ISSUE TITLE
Netlify checks on PRs are failing

### ISSUE THREAD

**Issue by jalseth** [open-policy-agent/conftest#640]
The Netlify checks on all recent PRs are failing, looks like due to the config using outdated versions of software that Netlify no longer includes in their build images.

For example (copied from https://app.netlify.com/sites/vibrant-villani-65041c/deploys/619293ef3fa2290007ff4461)

```
9:07:59 AM: Build ready to start
9:08:01 AM: build-image version: fd3b56fcdbaad56e70919e8a4b2da9b411ec3532 (xenial)
9:08:01 AM: build-image tag: v3.10.1
9:08:01 AM: buildbot version: 8b4b13a586b9f817ab478c0c44a476554bc16a2f
9:08:01 AM: Fetching cached dependencies
9:08:02 AM: Starting to download cache of 115.1MB
9:08:02 AM: Finished downloading cache in 926.958562ms
9:08:02 AM: Starting to extract cache
9:08:06 AM: Finished extracting cache in 3.610702073s
9:08:06 AM: Finished fetching cache in 4.574113837s
9:08:06 AM: Starting to prepare the repo for build
9:08:06 AM: Preparing Git Reference pull/638/head
9:08:07 AM: Parsing package.json dependencies
9:08:08 AM: Starting build script
9:08:08 AM: Installing dependencies
9:08:08 AM: Found Pipfile restoring Pipenv virtualenv
9:08:08 AM: Started restoring cached python virtualenv
9:08:08 AM: Finished restoring cached python virtualenv
9:08:09 AM: Started restoring cached node version
9:08:12 AM: Finished restoring cached node version
9:08:12 AM: v12.18.0 is already installed.
9:08:13 AM: Now using node v12.18.0 (npm v6.14.4)
9:08:13 AM: Started restoring cached build plugins
9:08:13 AM: Finished restoring cached build plugins
9:08:13 AM: Attempting ruby version 2.7.1, read from environment
9:08:14 AM: Started restoring cached ruby version
9:08:14 AM: Finished restoring cached ruby version
9:08:16 AM: Using ruby version 2.7.1
9:08:17 AM: Creating deploy upload records
9:08:17 AM: Using PHP version 5.6
9:08:18 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
9:08:17 AM: Installing dependencies from Pipfile
9:08:17 AM: Traceback (most recent call last):
9:08:17 AM:   File "/opt/buildhome/python2.7/bin/pipenv", line 5, in <module>
9:08:17 AM:     from pipenv import cli
9:08:17 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/__init__.py", line 22, in <module>
9:08:17 AM:     from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
9:08:17 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
9:08:17 AM:     from .compat import (
9:08:17 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
9:08:17 AM:     from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
9:08:17 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
9:08:17 AM:     from .tempfile import NamedTemporaryFile
9:08:17 AM:   File "/opt/buildhome/python2.7/local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
9:08:17 AM:     from backports.weakref import finalize
9:08:17 AM: ImportError: No module named weakref
9:08:17 AM: Error installing Pipenv dependencies
9:08:17 AM: Please see https://github.com/netlify/build-image/#included-software for current versions
9:08:17 AM: Build was terminated: Build script returned non-zero exit code: 1
9:08:18 AM: Failing build: Failed to build site
9:08:19 AM: Finished processing build request in 17.295144331s
```

**Comment by jpreese** [comment]
Should be resolved via https://github.com/open-policy-agent/conftest/pull/643

The Netlify build image and associated documentation seem.. way off. They say the default Python version is `3.8`, but I don't even see Python `3.8` installed on `netlify/build:v3.10.1` (the most recent image).

Furthermore the `pipenv` method refuses to use the Python version that's set, always using 2.7. However, looking through the run scripts in their Dockerfile repo you can forcefully set the Python runtime and the requirements using the `.txt` method.

One example: https://github.com/netlify/build-image/blob/focal/run-build-functions.sh#L413
